### PR TITLE
bugfix/launch simulator bugs

### LINKED ISSUE #83: Fixing bug with simulator-file
When clicking `Cancel` in Windows when you're chosing simulator file, there is an error-message.

### LINKED ISSUE #87: Fix bug when opening simulator first time
When you open the project the first time, the simulator opens too slow for the TCPclient and you get a ECONRESET or connection failed or something and have to try again.

### PR DESCRIPTION
**Pull request by Trebua**
Fixes bugs in #83 and #87 
* Error when server is not ready yet is handled by waiting 500ms before attempting to connect again
* Error when filepicker is canceled is handled by checking if any files were chosen before trying to launch it

close #83 
close #87

### CODE REVIEW

File: public/TCP/TCPClient.js [hunk 1]
```diff
@@ -3,16 +3,20 @@ const ROVPort = 5000;
 const { encodeData, decodeData } = require('./coding');
 const { sendReceivedMessage } = require('./../IPC');
 
+// Variable for keeping track of connection status - used to handle ECONNREFUSED error
+let connected = false;
```
Comment (eirikdahlen) [inline public/TCP/TCPClient.js]: Everything seems to work fine, but is `connected` ever set to `true`? I can't seem to find where it is, in any case.
